apiVersion: v1
kind: Namespace
metadata:
  name: testapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-python-deployment
  namespace: testapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-python
  template:
    metadata:
      labels:
        app: api-python
    spec:
      containers:
        - name: api-python
          image: testcr23062025.azurecr.io/api_python:1.0.0
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: api-python-service
  namespace: testapi
spec:
  type: LoadBalancer
  selector:
    app: api-python
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

